spring:
  application:
    name: worker-service
  kafka:
    producer:
      bootstrap-servers: ${kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${kafka.bootstrap-servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: kz.danekerscode.workerservice.service.MatrixTaskDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: kz.danekerscode.matrix.MatrixTask
            trusted:
              packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: kz.danekerscode.workerservice.service.MatrixTaskDeserializer
kafka:
  bootstrap-servers: localhost:9091,localhost:9093,localhost:9092
  topics:
    matrix-calculate: matrix-calculate
    matrix-calculate-result: matrix-calculate-result
server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true