global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'coordinator-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coordinator-service:8060']
        labels:
          application: 'Coordinator service Application'
  - job_name: 'worker-service-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker-service-1:8081']
        labels:
          application: 'Worker service1 Application'
  - job_name: 'worker-service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker-service-2:8081']
        labels:
          application: 'Worker service2 Application'
  - job_name: 'worker-service-3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker-service-3:8081']
        labels:
          application: 'Worker service3 Application'